version: "3.8"

services:
  # 1. SQL Server
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: renticar-sqlserver-${ASPNETCORE_ENVIRONMENT}
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=${SA_PASSWORD}
      - MSSQL_PID=Express
    restart: always
    ports:
      - "${SQL_PORT}:1433"
    volumes:
      - sqlserver_data_${ASPNETCORE_ENVIRONMENT}:/var/opt/mssql
    networks:
      - renticar-network

  # 2. Redis
  redis:
    image: redis:7.2-alpine
    container_name: renticar-redis-${ASPNETCORE_ENVIRONMENT}
    restart: always
    ports:
      - "${REDIS_PORT}:6379"
    volumes:
      - redis_data_${ASPNETCORE_ENVIRONMENT}:/data
    networks:
      - renticar-network

  # 3. RabbitMQ
  rabbitmq:
    image: masstransit/rabbitmq:latest
    container_name: renticar-rabbitmq-${ASPNETCORE_ENVIRONMENT}
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASSWORD}
    ports:
      - "${RABBITMQ_AMQP_PORT}:5672"
      - "${RABBITMQ_ADMIN_PORT}:15672"
    volumes:
      - rabbitmq_data_${ASPNETCORE_ENVIRONMENT}:/var/lib/rabbitmq
    networks:
      - renticar-network
    healthcheck:
      test: [ "CMD", "rabbitmq-diagnostics", "-q", "ping" ]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 10s

  # 4. .NET API
  api:
    image: ghcr.io/${GITHUB_REPOSITORY_OWNER}/renticar-api:${ASPNETCORE_ENVIRONMENT}
    container_name: renticar-api-${ASPNETCORE_ENVIRONMENT}
    restart: always
    environment:
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}
      - ASPNETCORE_URLS=http://+:80
    ports:
      - "${API_HTTP_PORT}:80"
    depends_on:
      sqlserver:
        condition: service_started
      redis:
        condition: service_started
      rabbitmq:
        condition: service_healthy
    volumes:
      - ./https:/https:ro
      - ./logs:/app/Logs
    networks:
      - renticar-network

  # 5. Sync Tool
  syncdatatool:
    image: ghcr.io/${GITHUB_REPOSITORY_OWNER}/renticar-sync:${ASPNETCORE_ENVIRONMENT}
    container_name: renticar-syncdatatool-${ASPNETCORE_ENVIRONMENT}
    restart: always
    environment:
      - DOTNET_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}
    depends_on:
      - sqlserver
      - api
    volumes:
      - ./logs:/app/Logs
    networks:
      - renticar-network

volumes:
  sqlserver_data_Production:
  sqlserver_data_Test:
  sqlserver_data_Development:
  redis_data_Production:
  redis_data_Test:
  redis_data_Development:
  rabbitmq_data_Production:
  rabbitmq_data_Test:
  rabbitmq_data_Development:


networks:
  renticar-network:
    driver: bridge