version: "3.8"

services:
  # SQL Server Database
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: renticar-sqlserver-${ASPNETCORE_ENVIRONMENT}
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=${SA_PASSWORD}
      - MSSQL_PID=Express
    restart: always
    ports:
      - "1433:1433"
    volumes:
      - sqlserver_data_${ASPNETCORE_ENVIRONMENT}:/var/opt/mssql
    networks:
      - renticar-network

  #Redis
  redis:
    image: redis:7.2-alpine
    container_name: renticar-redis-${ASPNETCORE_ENVIRONMENT}
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data_${ASPNETCORE_ENVIRONMENT}:/data
    networks:
      - renticar-network
  
  #RabbitMQ
  rabbitmq:
    image: masstransit/rabbitmq:latest
    container_name: renticar_rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASSWORD}
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data_${ASPNETCORE_ENVIRONMENT}:/var/lib/rabbitmq
    networks:
      - renticar-network
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 10s

  # .NET API Application
  api:
    build:
      context: ./NET_CarRentalSystem
      dockerfile: Dockerfile
    container_name: renticar-api-${ASPNETCORE_ENVIRONMENT}
    restart: always
    environment:
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}
      - ASPNETCORE_URLS=https://+:80;https://+:443
      - ASPNETCORE_HTTPS_PORT=${ASPNETCORE_HTTPS_PORT}
      - CERTIFICATE_PASSWORD=${CERTIFICATE_PASSWORD}
      - CERTIFICATE_PATH=${CERTIFICATE_PATH}
    ports:
      - "8080:80"
      - "8443:443"
    depends_on:
      sqlserver:
        condition: service_started
      redis:
        condition: service_started
      rabbitmq:
        condition: service_healthy
    volumes:
      - ./https:/https:ro
      - ./logs:/app/Logs
    networks:
      - renticar-network

  # .NET Sync Service
  syncdatatool:
    build:
      context: ./NET_CarRentalSystem.SyncDataTool
      dockerfile: Dockerfile
    container_name: renticar-syncdatatool-${ASPNETCORE_ENVIRONMENT}
    restart: always
    environment:
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}
    depends_on:
      - sqlserver
      - api
    volumes:
      - ./logs:/app/Logs
    networks:
      - renticar-network

volumes:
  sqlserver_data_Production:
  sqlserver_data_Test:
  sqlserver_data_Development:
  redis_data_Production:
  redis_data_Test:
  redis_data_Development:
  rabbitmq_data_Production:
  rabbitmq_data_Test:
  rabbitmq_data_Development:

networks:
  renticar-network:
    driver: bridge

