<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <UserSecretsId>76440d37-9829-4b86-9e06-2ade4eaf1db6</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\NET_CarRentalSystem.Domain\NET_CarRentalSystem.Domain.csproj" />
    <ProjectReference Include="..\NET_CarRentalSystem.Shared\NET_CarRentalSystem.Shared.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="FluentValidation.DependencyInjectionExtensions" Version="12.1.0" />
    <PackageReference Include="MassTransit.Abstractions" Version="8.5.6-develop.2396" />
    <PackageReference Include="MediatR" Version="11.0.0" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Features\Bookings\Consumers\" />
    <Folder Include="Features\Bookings\Events\" />
    <Folder Include="Features\Bookings\Queries\" />
  </ItemGroup>

</Project>
