name: Deploy Renticar

on:
  push:
    branches:
      - main
      - test
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: ${{ (github.ref == 'refs/heads/main' && 'production') || (github.ref == 'refs/heads/test' && 'test') || 'dev' }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      # ------------------------------------------------------------------
      # 1. PULL SOURCE CODE FROM GITHUB → VPS
      # ------------------------------------------------------------------
      - name: Pull Source Code to VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_PRIVATE_KEY }}
          passphrase: ${{ secrets.VPS_SSH_PASSPHRASE }}
          script: |
            PROJECT_PATH="${{ vars.VPS_PROJECT_PATH }}"
            ENV_NAME="${{ vars.ASPNETCORE_ENVIRONMENT }}"
            ENV_FILE=".env"
            APPSETTINGS_FILE="./NET_CarRentalSystem/appsettings.${ENV_NAME}.json"
            SYNC_APPSETTINGS="./NET_CarRentalSystem.SyncDataTool/appsettings.${ENV_NAME}.json"
            echo "=== Checking for existing Docker containers ==="
            if [ -d "$PROJECT_PATH" ]; then
              cd $PROJECT_PATH

              # Nếu file docker-compose.yml tồn tại → down trước
              if [ -f "docker-compose.yml" ]; then
                echo "--- Stopping existing containers ---"
                docker compose -f docker-compose.yml down || true
              fi
            fi

            echo "--- Cleanup old project files but keep folder: $PROJECT_PATH ---"
            # Nếu thư mục tồn tại → xoá toàn bộ file/folder con, trừ chính nó
            if [ -d "$PROJECT_PATH" ]; then
            rm -rf ${PROJECT_PATH:?}/*   # Xoá hết file con
            rm -rf ${PROJECT_PATH}/.* 2>/dev/null || true  # Xoá file ẩn (như .env, .gitignore)
            else
            mkdir -p "$PROJECT_PATH"
            fi  

            # Clone repo mới
            echo "--- Pull Latest Source ---"
            git clone ${{ secrets.REPO_URL }} ${PROJECT_PATH}
            cd ${PROJECT_PATH}
            git checkout ${{ github.ref_name }}

            # -------------------------------
            # 2. GENERATE .ENV FILE
            # -------------------------------
            echo "ASPNETCORE_ENVIRONMENT=${ENV_NAME}" > ${ENV_FILE}
            echo "SA_PASSWORD=${{ secrets.SA_PASSWORD }}" >> ${ENV_FILE}
            echo "RABBITMQ_USER=${{ secrets.RABBITMQ_USER }}" >> ${ENV_FILE}
            echo "RABBITMQ_PASSWORD=${{ secrets.RABBITMQ_PASSWORD }}" >> ${ENV_FILE}

            echo "SQL_PORT=${{ vars.SQL_PORT }}" >> ${ENV_FILE}
            echo "REDIS_PORT=${{ vars.REDIS_PORT }}" >> ${ENV_FILE}
            echo "RABBITMQ_AMQP_PORT=${{ vars.RABBITMQ_AMQP_PORT }}" >> ${ENV_FILE}
            echo "RABBITMQ_ADMIN_PORT=${{ vars.RABBITMQ_ADMIN_PORT }}" >> ${ENV_FILE}
            echo "API_HTTP_PORT=${{ vars.API_HTTP_PORT }}" >> ${ENV_FILE}
            echo "API_HTTPS_PORT=${{ vars.API_HTTPS_PORT }}" >> ${ENV_FILE}

            echo "ASPNETCORE_HTTPS_PORT=${{ vars.API_HTTPS_PORT }}" >> ${ENV_FILE}
            echo "CERTIFICATE_PASSWORD=${{ secrets.CERTIFICATE_PASSWORD }}" >> ${ENV_FILE}
            echo "CERTIFICATE_PATH=${{ vars.CERTIFICATE_PATH }}" >> ${ENV_FILE}

            # -------------------------------
            # 3. GENERATE APPSETTINGS.JSON
            # -------------------------------
            echo "--- Generating ${APPSETTINGS_FILE} ---"
            cat <<EOF > ${APPSETTINGS_FILE}
            {
              "ConnectionStrings": {
                "RenticarWriteDbContext": "${{ secrets.DB_WRITE_CONNECTION_STRING }}",
                "RenticarReadDbContext": "${{ secrets.DB_READ_CONNECTION_STRING }}",
                "Redis": "${{ secrets.REDIS_CONNECTION_STRING }}"
              },
              "DatabaseInitializationSettings": {
                "MaxRetries": ${{ vars.DB_MAX_RETRIES }},
                "DbRetryDelayInSeconds": ${{ vars.DB_RETRY_DELAY_SECONDS }}
              },
              "Logging": {
                "LogLevel": {
                  "Default": "Information",
                  "Microsoft.AspNetCore": "Warning"
                }
              },
              "Serilog": {
                "MinimumLevel": {
                  "Default": "Information",
                  "Override": {
                    "Microsoft": "Warning",
                    "System": "Warning"
                  }
                },
                "WriteTo": [
                  { "Name": "Console" },
                  {
                    "Name": "File",
                    "Args": {
                      "path": "Logs/log-.txt",
                      "rollingInterval": "Day",
                      "retainedFileCountLimit": 7,
                      "outputTemplate": "{Timestamp:yyyy-MM-dd HH:mm:ss.fff zzz} [{Level:u3}] {Message:lj}{NewLine}{Exception}"
                    }
                  }
                ],
                "Enrich": [ "FromLogContext", "WithMachineName", "WithThreadId" ]
              },
              "AllowedHosts": "*",
              "CloudinarySettings": {
                "CloudName": "${{ secrets.CLOUDINARY_CLOUD_NAME }}",
                "ApiKey": "${{ secrets.CLOUDINARY_API_KEY }}",
                "ApiSecret": "${{ secrets.CLOUDINARY_API_SECRET }}"
              },
              "Quartz": {
                "CheckToolAlive": {
                  "JobName": "${{ vars.QUARTZ_JOB_NAME }}",
                  "CronExpression": "${{ vars.QUARTZ_CRON_EXPRESSION }}"
                }
              },
              "Authentication": {
                "JwtSettings": {
                  "Key": "${{ secrets.JWT_SECRET }}",
                  "Issuer": "${{ vars.JWT_ISSUER }}",
                  "Audience": "${{ vars.JWT_AUDIENCE }}",
                  "AccessTokenDurationInMinutes": ${{ vars.JWT_ACCESS_TOKEN_DURATION }},
                  "RefreshTokenDurationInDays": ${{ vars.JWT_REFRESH_TOKEN_DURATION }}
                },
                "GoogleSettings": {
                  "ClientId": "${{ secrets.GOOGLE_CLIENT_ID }}",
                  "ClientSecret": "${{ secrets.GOOGLE_CLIENT_SECRET }}"
                }
              },
              "EmailSettings": {
                "Smtp": {
                  "Host": "${{ vars.EMAIL_SMTP_HOST }}",
                  "Port": ${{ vars.EMAIL_SMTP_PORT }},
                  "EmailAddress": "${{ vars.EMAIL_ADDRESS }}",
                  "Password": "${{ secrets.EMAIL_PASSWORD }}",
                  "EnableSsl": true,
                  "UserCredential": false
                },
                "FromEmailAddress": "${{ vars.EMAIL_ADDRESS }}",
                "FromDisplayName": "Renticar Support"
              },
              "Security": {
                "RsaSettings": {
                  "PublicKey": "${{ secrets.RSA_PUBLIC_KEY }}",
                  "PrivateKey": "${{ secrets.RSA_PRIVATE_KEY }}"
                },
                "AesSettings": {
                  "Key": "${{ secrets.AES_KEY }}",
                  "Iv": "${{ secrets.AES_IV }}"
                },
                "OtpSettings": {
                  "OtpExpiryMinutes": ${{ vars.OTP_EXPIRY_MINUTES }},
                  "MaxOtpAttempts": ${{ vars.MAX_OTP_ATTEMPTS }},
                  "KeyExpiryHours": ${{ vars.OTP_KEY_EXPIRY_HOURS }}
                },
                "ResetPasswordSettings": {
                  "TokenExpiryMinutes": ${{ vars.RESET_TOKEN_EXPIRY_MINUTES }},
                  "MaxTokenAttempts": ${{ vars.MAX_RESET_TOKEN_ATTEMPTS }},
                  "KeyExpiryHours": ${{ vars.RESET_KEY_EXPIRY_HOURS }},
                  "ClientUrl": "${{ vars.CLIENT_URL }}"
                }
              },
              "CorsSettings": {
                "Policies": {
                  "FrontendApp": {
                    "Origins": [ "${{ vars.FRONTEND_URL }}" ],
                    "Methods": ["*"],
                    "Headers": ["*"],
                    "AllowCredentials": true
                  }
                }
              },
              "ApiClient": {
                "MyApiSettings": {
                  "BaseUrl": "${{ vars.API_BASE_URL }}",
                  "DefaultTimeout": ${{ vars.API_DEFAULT_TIMEOUT }}
                }
              },
              "Payment": {
                "VnPaySettings": {
                  "ClientId": "${{ secrets.VNPAY_CLIENT_ID }}",
                  "ApiKey": "${{ secrets.VNPAY_API_KEY }}",
                  "BankCode": "${{ secrets.VNPAY_API_BANKCODE }}",
                  "AccountNumber": "${{ secrets.VNPAY_ACCOUNT_NUMBER }}",
                  "AccountName": "${{ secrets.VNPAY_ACCOUNT_NAME }}",
                  "ApiUrl": "${{ vars.VNPAY_API_URL }}",
                  "Template": "payment_template"
                }
              },
              "RabbitMQ": {
                "Host": "renticar-rabbitmq-${{ vars.ASPNETCORE_ENVIRONMENT }}",
                "Port": ${{ vars.RABBITMQ_INTERNAL_PORT }},
                "VirtualHost": "/",
                "Username": "${{ secrets.RABBITMQ_USER }}",
                "Password": "${{ secrets.RABBITMQ_PASSWORD }}"
              }
            }
            EOF
            
            # -------------------------------
            # 4. GENERATE SyncDataTool APPSETTINGS.JSON
            # -------------------------------
            echo "--- Generating ${SYNC_APPSETTINGS} ---"
            cat <<EOF > ${SYNC_APPSETTINGS}
            {
              "ConnectionStrings": {
                "RenticarWriteDbContext": "${{ secrets.DB_WRITE_CONNECTION_STRING }}",
                "RenticarReadDbContext": "${{ secrets.DB_READ_CONNECTION_STRING }}",
                "Redis": "${{ secrets.REDIS_CONNECTION_STRING }}"
              },
              "Logging": {
                "LogLevel": {
                  "Default": "Information",
                  "Microsoft.AspNetCore": "Warning"
                }
              },
              "Serilog": {
                "MinimumLevel": {
                  "Default": "Information",
                  "Override": {
                    "Microsoft": "Warning",
                    "System": "Warning"
                  }
                },
                "WriteTo": [
                  { "Name": "Console" },
                  {
                    "Name": "File",
                    "Args": {
                      "path": "Logs/log-.txt",
                      "rollingInterval": "Day",
                      "retainedFileCountLimit": 7,
                      "outputTemplate": "{Timestamp:yyyy-MM-dd HH:mm:ss.fff zzz} [{Level:u3}] {Message:lj}{NewLine}{Exception}"
                    }
                  }
                ],
                "Enrich": [ "FromLogContext", "WithMachineName", "WithThreadId" ]
              },
              "SyncDataToolSettings": {
                "SyncIntervalInSeconds": 2,
                "DbRetryDelayInSeconds": 5,
                "TablesToSync": [
                  { "TableName": "bookings", "PrimaryKeyColumn": "booking_id" },
                  { "TableName": "customers", "PrimaryKeyColumn": "customer_id" },
                  { "TableName": "locations", "PrimaryKeyColumn": "location_id" },
                  { "TableName": "transmissions", "PrimaryKeyColumn": "transmission_id" },
                  { "TableName": "vehicle_attributes", "PrimaryKeyColumn": "attribute_id" },
                  { "TableName": "vehicle_categories", "PrimaryKeyColumn": "vehicle_categorie_id" },
                  { "TableName": "vehicle_images", "PrimaryKeyColumn": "image_id" },
                  { "TableName": "vehicles", "PrimaryKeyColumn": "vehicle_id" },
                  { "TableName": "users", "PrimaryKeyColumn": "user_id" },
                  { "TableName": "role_claims", "PrimaryKeyColumn": "id" },
                  { "TableName": "roles", "PrimaryKeyColumn": "role_id" },
                  { "TableName": "user_sessions", "PrimaryKeyColumn": "user_session_id" },
                  { "TableName": "user_roles", "PrimaryKeyColumn": "user_role_id" },
                  { "TableName": "user_logins", "PrimaryKeyColumn": "user_login_id" },
                  { "TableName": "fuels", "PrimaryKeyColumn": "fuel_id" }
                ]
              }
            }
            EOF

      # ------------------------------------------------------------------
      # 2. RUN DOCKER COMPOSE ON VPS
      # ------------------------------------------------------------------
      - name: Run Docker Compose on VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_PRIVATE_KEY }}
          passphrase: ${{ secrets.VPS_SSH_PASSPHRASE }}
          script: |
            cd ${{ vars.VPS_PROJECT_PATH }}
            echo "--- Starting Docker Compose ---"
            docker compose build
            docker compose -f docker-compose.yml --env-file .env up -d --force-recreate --remove-orphans
            docker image prune -f